services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SGalinski\SgCookieOptin\:
    resource: '../Classes/*'

  SGalinski\SgCookieOptin\Command\GenerateStaticFilesCommand:
    tags:
      - name: 'console.command'
        command: 'sg_cookie_optin:generate_static_files'
        description: 'Generates the necessary JavaScript, JSON and CSS files.'

  SGalinski\SgCookieOptin\Command\DeleteUsageHistoryCommand:
    tags:
      - name: 'console.command'
        command: 'sg_cookie_optin:delete_usage_history'
        description: 'Deletes the optin usage history entries older than X days'
        
  SGalinski\SgCookieOptin\ViewHelpers:
    public: true

  TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper:
    public: true
    